[package]
name = "yew-taskboard"
version = "0.1.0"
authors = ["Kensuke Kubo <kensukekubo19@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.18.0"
js-sys = "0.3.55"
